server:
  port: 8004
spring:
  application:
    name: smartzipkin
management:
  metrics:
    web:
      server:
        auto-time-requests: false
zipkin:
  collector:
    rabbitmq:
      addresses: 192.168.10.3:5672
      username: root
      password: 123456
      queue: smartzipkin
logging:
  config: classpath:logback-spring-test.xml