server:
  port: 8004
spring:
  application:
    name: smartzipkin
  rabbitmq:
    connection-timeout: 10000
management:
  metrics:
    web:
      server:
        auto-time-requests: false
zipkin:
  collector:
    rabbitmq:
      addresses: 127.0.0.1:5672
      username: root
      password: 123456
      queue: smartzipkin
logging:
  config: classpath:logback-spring-dev.xml
