server:
  port: 9411
spring:
  application:
    name: smartzipkin
management:
  metrics:
    web:
      server:
        auto-time-requests: false
zipkin:
  collector:
    rabbitmq:
      addresses: 127.0.0.1:5672
      username: root
      password: 123456
      queue: smartzipkin