server:
  port: 9000
spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.10.3:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  application:
    name: smartkafka
  jackson:
    serialization:
      indent-output: true
      fail-on-empty-beans: false
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08
  zipkin:
    base-url: http://localhost:9411
    rabbitmq:
      queue: smartzipkin
      connection-timeout: 10000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

logging:
  path: /data/ftp/smartftp/log
  file: ${logging.path}smartkafka

kafka:
  jaas:
    conf:
      path: /data/project/smarthelper/smartkafka/src/main/resources/kafka_client_jaas.conf



