server:
  port: 9000
spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.10.3:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  application:
    name: smartproducer
  jackson:
    serialization:
      indent-output: true
      fail-on-empty-beans: false
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

logging:
  path: E://log/
  file: ${logging.path}smartproducer
