server:
  port: 8088
spring:
  application:
    name: smartcache
  redis:
    database: 0
    host: 192.168.10.3
    port: 6379
    password: 123456
    timeout: 1000
  zipkin:
    base-url: http://localhost:9411
    rabbitmq:
      queue: smartzipkin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  config: classpath:logback-spring.xml